name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:    
    paths-ignore:
      - 'README.md'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build --tag todo-app:test --target test .
    - run: docker run todo-app:test

  deploy:
      name: push to Docker Hub and Trigger App Service Deploy
      runs-on: ubuntu-latest
      needs: build
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/exercise-9' }}
      steps:
        - uses: actions/checkout@v2
        - run: echo hello deploy
        - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - run: docker build --tag abhilashjagityla1/todo-app:prod --target production
      - run: dicker push abhilashjagityla1/todo-app:prod